# Generated by Django 4.2.4 on 2023-08-16 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='다음 단어 ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='prev_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='이전 단어 ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
