# Generated by Django 4.2.4 on 2023-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='next_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='다음 저장한 단어 ID'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='prev_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='이전 저장한 단어 ID'),
        ),
    ]
